version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: notes_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2244
      - POSTGRES_DB=notes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  app:
    container_name: notes_fastapi_app
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:2244@db:5432/notes_db?client_encoding=utf8"

volumes:
  postgres_data: